# coding: utf-8

"""
SkyLink - Contacts Service API

Internal microservice integrating with Google People API for contacts. Includes Auth and Health endpoints.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import BaseModel, Field, StrictStr

from skylink.models.contacts.google_person_addresses_inner import GooglePersonAddressesInner
from skylink.models.contacts.google_person_birthdays_inner import GooglePersonBirthdaysInner
from skylink.models.contacts.google_person_email_addresses_inner import (
    GooglePersonEmailAddressesInner,
)
from skylink.models.contacts.google_person_metadata import GooglePersonMetadata
from skylink.models.contacts.google_person_names_inner import GooglePersonNamesInner
from skylink.models.contacts.google_person_organizations_inner import (
    GooglePersonOrganizationsInner,
)
from skylink.models.contacts.google_person_phone_numbers_inner import (
    GooglePersonPhoneNumbersInner,
)
from skylink.models.contacts.google_person_photos_inner import GooglePersonPhotosInner

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class GooglePerson(BaseModel):
    """
    Subset of Google `Person` schema, controlled by `person_fields`.
    """  # noqa: E501

    resource_name: Optional[StrictStr] = Field(default=None, alias="resourceName")
    etag: Optional[StrictStr] = None
    names: Optional[List[GooglePersonNamesInner]] = None
    email_addresses: Optional[List[GooglePersonEmailAddressesInner]] = Field(
        default=None,
        alias="emailAddresses",
    )
    phone_numbers: Optional[List[GooglePersonPhoneNumbersInner]] = Field(
        default=None,
        alias="phoneNumbers",
    )
    photos: Optional[List[GooglePersonPhotosInner]] = None
    organizations: Optional[List[GooglePersonOrganizationsInner]] = None
    birthdays: Optional[List[GooglePersonBirthdaysInner]] = None
    addresses: Optional[List[GooglePersonAddressesInner]] = None
    metadata: Optional[GooglePersonMetadata] = None
    __properties: ClassVar[List[str]] = [
        "resourceName",
        "etag",
        "names",
        "emailAddresses",
        "phoneNumbers",
        "photos",
        "organizations",
        "birthdays",
        "addresses",
        "metadata",
    ]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GooglePerson from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        # call `to_dict()` on each element in names
        _items = []
        if self.names:
            for _item in self.names:
                if _item:
                    _items.append(_item.to_dict())
            _dict["names"] = _items
        # call `to_dict()` on each element in email_addresses
        _items = []
        if self.email_addresses:
            for _item in self.email_addresses:
                if _item:
                    _items.append(_item.to_dict())
            _dict["emailAddresses"] = _items
        # call `to_dict()` on each element in phone_numbers
        _items = []
        if self.phone_numbers:
            for _item in self.phone_numbers:
                if _item:
                    _items.append(_item.to_dict())
            _dict["phoneNumbers"] = _items
        # call `to_dict()` on each element in photos
        _items = []
        if self.photos:
            for _item in self.photos:
                if _item:
                    _items.append(_item.to_dict())
            _dict["photos"] = _items
        # call `to_dict()` on each element in organizations
        _items = []
        if self.organizations:
            for _item in self.organizations:
                if _item:
                    _items.append(_item.to_dict())
            _dict["organizations"] = _items
        # call `to_dict()` on each element in birthdays
        _items = []
        if self.birthdays:
            for _item in self.birthdays:
                if _item:
                    _items.append(_item.to_dict())
            _dict["birthdays"] = _items
        # call `to_dict()` on each element in addresses
        _items = []
        if self.addresses:
            for _item in self.addresses:
                if _item:
                    _items.append(_item.to_dict())
            _dict["addresses"] = _items
        # override default output by calling `to_dict()` on metadata
        if self.metadata:
            _dict["metadata"] = self.metadata.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GooglePerson from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "resourceName": obj.get("resourceName"),
                "etag": obj.get("etag"),
                "names": (
                    [GooglePersonNamesInner.from_dict(_item) for _item in obj.get("names")]
                    if obj.get("names") is not None
                    else None
                ),
                "emailAddresses": (
                    [
                        GooglePersonEmailAddressesInner.from_dict(_item)
                        for _item in obj.get("emailAddresses")
                    ]
                    if obj.get("emailAddresses") is not None
                    else None
                ),
                "phoneNumbers": (
                    [
                        GooglePersonPhoneNumbersInner.from_dict(_item)
                        for _item in obj.get("phoneNumbers")
                    ]
                    if obj.get("phoneNumbers") is not None
                    else None
                ),
                "photos": (
                    [GooglePersonPhotosInner.from_dict(_item) for _item in obj.get("photos")]
                    if obj.get("photos") is not None
                    else None
                ),
                "organizations": (
                    [
                        GooglePersonOrganizationsInner.from_dict(_item)
                        for _item in obj.get("organizations")
                    ]
                    if obj.get("organizations") is not None
                    else None
                ),
                "birthdays": (
                    [GooglePersonBirthdaysInner.from_dict(_item) for _item in obj.get("birthdays")]
                    if obj.get("birthdays") is not None
                    else None
                ),
                "addresses": (
                    [GooglePersonAddressesInner.from_dict(_item) for _item in obj.get("addresses")]
                    if obj.get("addresses") is not None
                    else None
                ),
                "metadata": (
                    GooglePersonMetadata.from_dict(obj.get("metadata"))
                    if obj.get("metadata") is not None
                    else None
                ),
            }
        )
        return _obj
