"""Add oauth_tokens table

Revision ID: 68b6b750c581
Revises:
Create Date: 2025-11-10 14:26:46.902986

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from contacts.models import JSONEncodedList

# revision identifiers, used by Alembic.
revision: str = "68b6b750c581"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_tokens",
        sa.Column("aircraft_id", sa.UUID(), nullable=False, comment="Aircraft UUID from JWT token"),
        sa.Column("provider", sa.String(length=50), nullable=False, comment="OAuth provider name"),
        sa.Column(
            "access_token",
            sa.Text(),
            nullable=False,
            comment="Google access token (plaintext, short TTL)",
        ),
        sa.Column(
            "refresh_token",
            sa.Text(),
            nullable=False,
            comment="Google refresh token (AES-256-GCM encrypted)",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Access token expiration (UTC)",
        ),
        sa.Column(
            "scopes", JSONEncodedList(), nullable=False, comment="List of OAuth scopes granted"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Record creation timestamp (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Record last update timestamp (UTC)",
        ),
        sa.PrimaryKeyConstraint("aircraft_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth_tokens")
    # ### end Alembic commands ###
