# coding: utf-8

"""
SkyLink API

SkyLink Connected Aircraft Platform - MVP  Security by Design implementation with JWT authentication, rate limiting, and strict input validation.

The version of the OpenAPI document: 0.6.2
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List

from pydantic import BaseModel, Field, StrictStr, field_validator

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class StartGoogleOAuth200Response(BaseModel):
    """
    StartGoogleOAuth200Response
    """  # noqa: E501

    authorization_url: StrictStr = Field(
        description="Complete Google OAuth URL (including state, code_challenge, etc.)."
    )
    state: StrictStr = Field(description="Anti-CSRF state to return unchanged to the callback.")
    code_challenge_method: StrictStr
    __properties: ClassVar[List[str]] = ["authorization_url", "state", "code_challenge_method"]

    @field_validator("code_challenge_method")
    def code_challenge_method_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ("S256",):
            raise ValueError("must be one of enum values ('S256')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StartGoogleOAuth200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of StartGoogleOAuth200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "authorization_url": obj.get("authorization_url"),
                "state": obj.get("state"),
                "code_challenge_method": obj.get("code_challenge_method"),
            }
        )
        return _obj
