# coding: utf-8

"""
SkyLink API

SkyLink Connected Aircraft Platform - MVP  Security by Design implementation with JWT authentication, rate limiting, and strict input validation.

The version of the OpenAPI document: 0.6.2
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing_extensions import Annotated

from skylink.models.gateway.telemetry_event_metrics_cabin_pressure import (
    TelemetryEventMetricsCabinPressure,
)
from skylink.models.gateway.telemetry_event_metrics_climate_control import (
    TelemetryEventMetricsClimateControl,
)
from skylink.models.gateway.telemetry_event_metrics_engine_status import (
    TelemetryEventMetricsEngineStatus,
)
from skylink.models.gateway.telemetry_event_metrics_flight_controls import (
    TelemetryEventMetricsFlightControls,
)
from skylink.models.gateway.telemetry_event_metrics_gps import TelemetryEventMetricsGps
from skylink.models.gateway.telemetry_event_metrics_lights_status import (
    TelemetryEventMetricsLightsStatus,
)

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class TelemetryEventMetrics(BaseModel):
    """
    Complete set of real-time aircraft telemetry metrics
    """  # noqa: E501

    speed: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Aircraft speed in km/h"
    )
    altitude: Optional[
        Union[
            Annotated[float, Field(le=100, strict=True, ge=0)],
            Annotated[int, Field(le=100, strict=True, ge=0)],
        ]
    ] = Field(default=None, description="Altitude in feet")
    engine_temp: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Engine temperature in °C"
    )
    engine_status: Optional[TelemetryEventMetricsEngineStatus] = None
    oil_level: Optional[
        Union[
            Annotated[float, Field(le=100, strict=True, ge=0)],
            Annotated[int, Field(le=100, strict=True, ge=0)],
        ]
    ] = Field(default=None, description="Engine oil level percentage")
    outside_temp: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="External ambient temperature in °C"
    )
    brake_status: Optional[StrictStr] = Field(default=None, description="Brake system status")
    battery_level: Optional[
        Union[
            Annotated[float, Field(le=100, strict=True, ge=0)],
            Annotated[int, Field(le=100, strict=True, ge=0)],
        ]
    ] = Field(default=None, description="Battery charge level percentage")
    gps: Optional[TelemetryEventMetricsGps] = None
    airbag_status: Optional[StrictStr] = Field(default=None, description="Airbag system status")
    flight_controls: Optional[TelemetryEventMetricsFlightControls] = None
    lights_status: Optional[TelemetryEventMetricsLightsStatus] = None
    climate_control: Optional[TelemetryEventMetricsClimateControl] = None
    cabin_pressure: Optional[TelemetryEventMetricsCabinPressure] = None
    __properties: ClassVar[List[str]] = [
        "speed",
        "altitude",
        "engine_temp",
        "engine_status",
        "oil_level",
        "outside_temp",
        "brake_status",
        "battery_level",
        "gps",
        "airbag_status",
        "flight_controls",
        "lights_status",
        "climate_control",
        "cabin_pressure",
    ]

    @field_validator("brake_status")
    def brake_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in (
            "ok",
            "worn",
            "malfunction",
        ):
            raise ValueError("must be one of enum values ('ok', 'worn', 'malfunction')")
        return value

    @field_validator("airbag_status")
    def airbag_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in (
            "armed",
            "deployed",
            "fault",
        ):
            raise ValueError("must be one of enum values ('armed', 'deployed', 'fault')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TelemetryEventMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of engine_status
        if self.engine_status:
            _dict["engine_status"] = self.engine_status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gps
        if self.gps:
            _dict["gps"] = self.gps.to_dict()
        # override the default output from pydantic by calling `to_dict()` of flight_controls
        if self.flight_controls:
            _dict["flight_controls"] = self.flight_controls.to_dict()
        # override the default output from pydantic by calling `to_dict()` of lights_status
        if self.lights_status:
            _dict["lights_status"] = self.lights_status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of climate_control
        if self.climate_control:
            _dict["climate_control"] = self.climate_control.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cabin_pressure
        if self.cabin_pressure:
            _dict["cabin_pressure"] = self.cabin_pressure.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TelemetryEventMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "speed": obj.get("speed"),
                "altitude": obj.get("altitude"),
                "engine_temp": obj.get("engine_temp"),
                "engine_status": (
                    TelemetryEventMetricsEngineStatus.from_dict(obj.get("engine_status"))
                    if obj.get("engine_status") is not None
                    else None
                ),
                "oil_level": obj.get("oil_level"),
                "outside_temp": obj.get("outside_temp"),
                "brake_status": obj.get("brake_status"),
                "battery_level": obj.get("battery_level"),
                "gps": (
                    TelemetryEventMetricsGps.from_dict(obj.get("gps"))
                    if obj.get("gps") is not None
                    else None
                ),
                "airbag_status": obj.get("airbag_status"),
                "flight_controls": (
                    TelemetryEventMetricsFlightControls.from_dict(obj.get("flight_controls"))
                    if obj.get("flight_controls") is not None
                    else None
                ),
                "lights_status": (
                    TelemetryEventMetricsLightsStatus.from_dict(obj.get("lights_status"))
                    if obj.get("lights_status") is not None
                    else None
                ),
                "climate_control": (
                    TelemetryEventMetricsClimateControl.from_dict(obj.get("climate_control"))
                    if obj.get("climate_control") is not None
                    else None
                ),
                "cabin_pressure": (
                    TelemetryEventMetricsCabinPressure.from_dict(obj.get("cabin_pressure"))
                    if obj.get("cabin_pressure") is not None
                    else None
                ),
            }
        )
        return _obj
