# coding: utf-8

"""
SkyLink API

SkyLink Connected Aircraft Platform - MVP  Security by Design implementation with JWT authentication, rate limiting, and strict input validation.

The version of the OpenAPI document: 0.6.2
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class WeatherDataLocation(BaseModel):
    """
    Location metadata for the requested coordinates.
    """  # noqa: E501

    name: StrictStr = Field(description="Human-readable city/locality name (localized per `lang`).")
    region: StrictStr = Field(description="Administrative region or state (localized per `lang`).")
    country: StrictStr = Field(description="Country name (localized per `lang`).")
    lat: Union[StrictFloat, StrictInt] = Field(
        description="Latitude of the location in decimal degrees."
    )
    lon: Union[StrictFloat, StrictInt] = Field(
        description="Longitude of the location in decimal degrees."
    )
    tz_id: StrictStr = Field(description="IANA time zone identifier for the location.")
    localtime_epoch: StrictInt = Field(
        description="Local time as a Unix epoch (seconds) at the location."
    )
    localtime: StrictStr = Field(description='Local time as a formatted string "YYYY-MM-DD HH:mm".')
    __properties: ClassVar[List[str]] = [
        "name",
        "region",
        "country",
        "lat",
        "lon",
        "tz_id",
        "localtime_epoch",
        "localtime",
    ]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WeatherDataLocation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WeatherDataLocation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "region": obj.get("region"),
                "country": obj.get("country"),
                "lat": obj.get("lat"),
                "lon": obj.get("lon"),
                "tz_id": obj.get("tz_id"),
                "localtime_epoch": obj.get("localtime_epoch"),
                "localtime": obj.get("localtime"),
            }
        )
        return _obj
