# coding: utf-8

"""
SkyLink API

SkyLink Connected Aircraft Platform - MVP  Security by Design implementation with JWT authentication, rate limiting, and strict input validation.

The version of the OpenAPI document: 0.6.2
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class WeatherDataCurrentAirQuality(BaseModel):
    """
    Air quality metrics (may be absent if provider disabled).
    """  # noqa: E501

    co: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Carbon monoxide concentration."
    )
    no2: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Nitrogen dioxide concentration."
    )
    o3: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Ozone concentration."
    )
    so2: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Sulfur dioxide concentration."
    )
    pm2_5: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Fine particulate matter ≤2.5μm concentration."
    )
    pm10: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Particulate matter ≤10μm concentration."
    )
    us_epa_index: Optional[StrictInt] = Field(
        default=None, description="US EPA AQI category index.", alias="us-epa-index"
    )
    gb_defra_index: Optional[StrictInt] = Field(
        default=None, description="UK DEFRA AQI category index.", alias="gb-defra-index"
    )
    __properties: ClassVar[List[str]] = [
        "co",
        "no2",
        "o3",
        "so2",
        "pm2_5",
        "pm10",
        "us-epa-index",
        "gb-defra-index",
    ]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WeatherDataCurrentAirQuality from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WeatherDataCurrentAirQuality from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "co": obj.get("co"),
                "no2": obj.get("no2"),
                "o3": obj.get("o3"),
                "so2": obj.get("so2"),
                "pm2_5": obj.get("pm2_5"),
                "pm10": obj.get("pm10"),
                "us-epa-index": obj.get("us-epa-index"),
                "gb-defra-index": obj.get("gb-defra-index"),
            }
        )
        return _obj
