# coding: utf-8

"""
SkyLink - Telemetry Service API

Internal microservice handling aircraft telemetry ingestion with idempotency. Includes Auth and Health endpoints.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import BaseModel, StrictBool

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class TelemetryEventMetricsLightsStatus(BaseModel):
    """
    Aircraft lights state
    """  # noqa: E501

    headlights: Optional[StrictBool] = None
    brake_lights: Optional[StrictBool] = None
    turn_signal_left: Optional[StrictBool] = None
    turn_signal_right: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = [
        "headlights",
        "brake_lights",
        "turn_signal_left",
        "turn_signal_right",
    ]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
        "extra": "forbid",
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TelemetryEventMetricsLightsStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TelemetryEventMetricsLightsStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "headlights": obj.get("headlights"),
                "brake_lights": obj.get("brake_lights"),
                "turn_signal_left": obj.get("turn_signal_left"),
                "turn_signal_right": obj.get("turn_signal_right"),
            }
        )
        return _obj
