# coding: utf-8

"""
SkyLink - Telemetry Service API

Internal microservice handling vehicle telemetry ingestion with idempotency. Includes Auth and Health endpoints.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing_extensions import Annotated

from skylink.models.telemetry.telemetry_event_metrics_climate_control import (
    TelemetryEventMetricsClimateControl,
)
from skylink.models.telemetry.telemetry_event_metrics_gps import TelemetryEventMetricsGps
from skylink.models.telemetry.telemetry_event_metrics_lights_status import (
    TelemetryEventMetricsLightsStatus,
)
from skylink.models.telemetry.telemetry_event_metrics_seatbelt_status import (
    TelemetryEventMetricsSeatbeltStatus,
)
from skylink.models.telemetry.telemetry_event_metrics_tire_pressure import (
    TelemetryEventMetricsTirePressure,
)
from skylink.models.telemetry.telemetry_event_metrics_transmission import (
    TelemetryEventMetricsTransmission,
)

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class TelemetryEventMetrics(BaseModel):
    """
    Complete set of real-time vehicle telemetry metrics
    """  # noqa: E501

    speed: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Vehicle speed in km/h",
    )
    fuel_level: Optional[
        Union[
            Annotated[float, Field(le=100, strict=True, ge=0)],
            Annotated[int, Field(le=100, strict=True, ge=0)],
        ]
    ] = Field(
        default=None,
        description="Fuel level percentage",
    )
    engine_temp: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Engine temperature in °C",
    )
    tire_pressure: Optional[TelemetryEventMetricsTirePressure] = None
    oil_level: Optional[
        Union[
            Annotated[float, Field(le=100, strict=True, ge=0)],
            Annotated[int, Field(le=100, strict=True, ge=0)],
        ]
    ] = Field(
        default=None,
        description="Engine oil level percentage",
    )
    outside_temp: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="External ambient temperature in °C",
    )
    brake_status: Optional[StrictStr] = Field(
        default=None,
        description="Brake system status",
    )
    battery_level: Optional[
        Union[
            Annotated[float, Field(le=100, strict=True, ge=0)],
            Annotated[int, Field(le=100, strict=True, ge=0)],
        ]
    ] = Field(
        default=None,
        description="Battery charge level percentage",
    )
    gps: Optional[TelemetryEventMetricsGps] = None
    airbag_status: Optional[StrictStr] = Field(
        default=None,
        description="Airbag system status",
    )
    transmission: Optional[TelemetryEventMetricsTransmission] = None
    lights_status: Optional[TelemetryEventMetricsLightsStatus] = None
    climate_control: Optional[TelemetryEventMetricsClimateControl] = None
    seatbelt_status: Optional[TelemetryEventMetricsSeatbeltStatus] = None
    __properties: ClassVar[List[str]] = [
        "speed",
        "fuel_level",
        "engine_temp",
        "tire_pressure",
        "oil_level",
        "outside_temp",
        "brake_status",
        "battery_level",
        "gps",
        "airbag_status",
        "transmission",
        "lights_status",
        "climate_control",
        "seatbelt_status",
    ]

    @field_validator("brake_status")
    def brake_status_validate_enum(cls, value):  # noqa: N805
        """Validates the enum"""
        if value is None:
            return value

        if value not in (
            "ok",
            "worn",
            "malfunction",
        ):
            raise ValueError("must be one of enum values ('ok', 'worn', 'malfunction')")
        return value

    @field_validator("airbag_status")
    def airbag_status_validate_enum(cls, value):  # noqa: N805
        """Validates the enum"""
        if value is None:
            return value

        if value not in (
            "armed",
            "deployed",
            "fault",
        ):
            raise ValueError("must be one of enum values ('armed', 'deployed', 'fault')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
        "extra": "forbid",
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TelemetryEventMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        # override default output by calling `to_dict()` on tire_pressure
        if self.tire_pressure:
            _dict["tire_pressure"] = self.tire_pressure.to_dict()
        # override default output by calling `to_dict()` on gps
        if self.gps:
            _dict["gps"] = self.gps.to_dict()
        # override default output by calling `to_dict()` on transmission
        if self.transmission:
            _dict["transmission"] = self.transmission.to_dict()
        # override default output by calling `to_dict()` on lights_status
        if self.lights_status:
            _dict["lights_status"] = self.lights_status.to_dict()
        # override default output by calling `to_dict()` on climate_control
        if self.climate_control:
            _dict["climate_control"] = self.climate_control.to_dict()
        # override default output by calling `to_dict()` on seatbelt_status
        if self.seatbelt_status:
            _dict["seatbelt_status"] = self.seatbelt_status.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TelemetryEventMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "speed": obj.get("speed"),
                "fuel_level": obj.get("fuel_level"),
                "engine_temp": obj.get("engine_temp"),
                "tire_pressure": (
                    TelemetryEventMetricsTirePressure.from_dict(obj.get("tire_pressure"))
                    if obj.get("tire_pressure") is not None
                    else None
                ),
                "oil_level": obj.get("oil_level"),
                "outside_temp": obj.get("outside_temp"),
                "brake_status": obj.get("brake_status"),
                "battery_level": obj.get("battery_level"),
                "gps": (
                    TelemetryEventMetricsGps.from_dict(obj.get("gps"))
                    if obj.get("gps") is not None
                    else None
                ),
                "airbag_status": obj.get("airbag_status"),
                "transmission": (
                    TelemetryEventMetricsTransmission.from_dict(obj.get("transmission"))
                    if obj.get("transmission") is not None
                    else None
                ),
                "lights_status": (
                    TelemetryEventMetricsLightsStatus.from_dict(obj.get("lights_status"))
                    if obj.get("lights_status") is not None
                    else None
                ),
                "climate_control": (
                    TelemetryEventMetricsClimateControl.from_dict(obj.get("climate_control"))
                    if obj.get("climate_control") is not None
                    else None
                ),
                "seatbelt_status": (
                    TelemetryEventMetricsSeatbeltStatus.from_dict(obj.get("seatbelt_status"))
                    if obj.get("seatbelt_status") is not None
                    else None
                ),
            }
        )
        return _obj
