# coding: utf-8

"""
SkyLink - Telemetry Service API

Internal microservice handling aircraft telemetry ingestion with idempotency. Includes Auth and Health endpoints.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import BaseModel, StrictBool

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class TelemetryEventMetricsCabinPressure(BaseModel):
    """
    Cabin pressure indicators
    """  # noqa: E501

    driver: Optional[StrictBool] = None
    passenger_front: Optional[StrictBool] = None
    rear_left: Optional[StrictBool] = None
    rear_center: Optional[StrictBool] = None
    rear_right: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = [
        "driver",
        "passenger_front",
        "rear_left",
        "rear_center",
        "rear_right",
    ]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
        "extra": "forbid",
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TelemetryEventMetricsCabinPressure from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TelemetryEventMetricsCabinPressure from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "driver": obj.get("driver"),
                "passenger_front": obj.get("passenger_front"),
                "rear_left": obj.get("rear_left"),
                "rear_center": obj.get("rear_center"),
                "rear_right": obj.get("rear_right"),
            }
        )
        return _obj
