# coding: utf-8

"""
SkyLink - Weather Service API

Internal microservice exposing current weather retrieval. Includes Auth (JWT issuance for service-to-service) and Health endpoints.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List, Optional, Union

from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr

from skylink.models.weather.weather_data_current_air_quality import WeatherDataCurrentAirQuality
from skylink.models.weather.weather_data_current_condition import WeatherDataCurrentCondition

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class WeatherDataCurrent(BaseModel):
    """
    Snapshot of current weather conditions.
    """  # noqa: E501

    last_updated_epoch: StrictInt
    last_updated: StrictStr
    temp_c: Union[StrictFloat, StrictInt]
    temp_f: Union[StrictFloat, StrictInt]
    is_day: StrictInt
    condition: WeatherDataCurrentCondition
    wind_mph: Union[StrictFloat, StrictInt]
    wind_kph: Union[StrictFloat, StrictInt]
    wind_degree: Union[StrictFloat, StrictInt]
    wind_dir: StrictStr
    pressure_mb: Union[StrictFloat, StrictInt]
    pressure_in: Union[StrictFloat, StrictInt]
    precip_mm: Union[StrictFloat, StrictInt]
    precip_in: Union[StrictFloat, StrictInt]
    humidity: Union[StrictFloat, StrictInt]
    cloud: Union[StrictFloat, StrictInt]
    feelslike_c: Union[StrictFloat, StrictInt]
    feelslike_f: Union[StrictFloat, StrictInt]
    vis_km: Union[StrictFloat, StrictInt]
    vis_miles: Union[StrictFloat, StrictInt]
    uv: StrictInt
    gust_mph: Union[StrictFloat, StrictInt]
    gust_kph: Union[StrictFloat, StrictInt]
    air_quality: Optional[WeatherDataCurrentAirQuality] = None
    __properties: ClassVar[List[str]] = [
        "last_updated_epoch",
        "last_updated",
        "temp_c",
        "temp_f",
        "is_day",
        "condition",
        "wind_mph",
        "wind_kph",
        "wind_degree",
        "wind_dir",
        "pressure_mb",
        "pressure_in",
        "precip_mm",
        "precip_in",
        "humidity",
        "cloud",
        "feelslike_c",
        "feelslike_f",
        "vis_km",
        "vis_miles",
        "uv",
        "gust_mph",
        "gust_kph",
        "air_quality",
    ]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WeatherDataCurrent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        # override default output by calling `to_dict()` on condition
        if self.condition:
            _dict["condition"] = self.condition.to_dict()
        # override default output by calling `to_dict()` on air_quality
        if self.air_quality:
            _dict["air_quality"] = self.air_quality.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WeatherDataCurrent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "last_updated_epoch": obj.get("last_updated_epoch"),
                "last_updated": obj.get("last_updated"),
                "temp_c": obj.get("temp_c"),
                "temp_f": obj.get("temp_f"),
                "is_day": obj.get("is_day"),
                "condition": (
                    WeatherDataCurrentCondition.from_dict(obj.get("condition"))
                    if obj.get("condition") is not None
                    else None
                ),
                "wind_mph": obj.get("wind_mph"),
                "wind_kph": obj.get("wind_kph"),
                "wind_degree": obj.get("wind_degree"),
                "wind_dir": obj.get("wind_dir"),
                "pressure_mb": obj.get("pressure_mb"),
                "pressure_in": obj.get("pressure_in"),
                "precip_mm": obj.get("precip_mm"),
                "precip_in": obj.get("precip_in"),
                "humidity": obj.get("humidity"),
                "cloud": obj.get("cloud"),
                "feelslike_c": obj.get("feelslike_c"),
                "feelslike_f": obj.get("feelslike_f"),
                "vis_km": obj.get("vis_km"),
                "vis_miles": obj.get("vis_miles"),
                "uv": obj.get("uv"),
                "gust_mph": obj.get("gust_mph"),
                "gust_kph": obj.get("gust_kph"),
                "air_quality": (
                    WeatherDataCurrentAirQuality.from_dict(obj.get("air_quality"))
                    if obj.get("air_quality") is not None
                    else None
                ),
            }
        )
        return _obj
