# coding: utf-8

"""
SkyLink - Weather Service API

Internal microservice exposing current weather retrieval. Includes Auth (JWT issuance for service-to-service) and Health endpoints.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
from typing import Any, ClassVar, Dict, List

from pydantic import BaseModel

from skylink.models.weather.weather_data_current import WeatherDataCurrent
from skylink.models.weather.weather_data_location import WeatherDataLocation

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class WeatherData(BaseModel):
    """
    Current weather response.
    """  # noqa: E501

    location: WeatherDataLocation
    current: WeatherDataCurrent
    __properties: ClassVar[List[str]] = ["location", "current"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WeatherData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        # override default output by calling `to_dict()` on location
        if self.location:
            _dict["location"] = self.location.to_dict()
        # override default output by calling `to_dict()` on current
        if self.current:
            _dict["current"] = self.current.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WeatherData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "location": (
                    WeatherDataLocation.from_dict(obj.get("location"))
                    if obj.get("location") is not None
                    else None
                ),
                "current": (
                    WeatherDataCurrent.from_dict(obj.get("current"))
                    if obj.get("current") is not None
                    else None
                ),
            }
        )
        return _obj
